apiVersion: v1
kind: Service
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-svc
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
      nodePort: 30002
  selector:
    app: resultserver-deploy
  type: NodePort
